### PR TITLE
Chained promises should be marked as handled. Fixes #10

### LINKED ISSUE #10: unhandledRejection algorithm incomplete
``` js
var deferred = Promise.defer();
deferred
  .then()
  .then()  // only this one promise in the chain ends up getting marked as "handled"
  .catch(); 
```

### PR DESCRIPTION
**Pull request by jamestalmage**
This is the way Node and bluebird handle it. Way easier implementation than #11.

### CODE REVIEW

**Comment by TrySound** [comment]
Too simple :))

**Comment by jamestalmage** [comment]
I read the Node documentation and too them at their word. My mistake.

**Comment by floatdrop** [comment]
That's much better :)

**Comment by TrySound** [comment]
@floatdrop  Patch release?

**Comment by floatdrop** [comment]
@TrySound yes

**Comment by TrySound** [comment]
@jamestalmage Seems like on windows this fix doesn't work. But previous worked
https://github.com/davidtheclark/cosmiconfig/pull/17

**Comment by jamestalmage** [comment]
WINNNDOOOWS!!!

@floatdrop Can you set up AppVeyor tests?

**Comment by jamestalmage** [comment]
@TrySound 

Where are you getting windows failures? AppVeyor?

Try running the old `pinkie` fix on Windows a couple times. There really should be no reason one works an the other doesn't.

Also - if you are using `pinkie-promise`, you are not using pinkie on newer versions of Node. You are using native promises.

**Comment by floatdrop** [comment]
@jamestalmage done :smile:

**Comment by TrySound** [comment]
@jamestalmage It fails only on node 0.10 in our tests

**Comment by jamestalmage** [comment]
OK, I found your AppVeyor build.

Yeah that looks not good. Can you whip up a small reproduction and submit it as an AVA PR? There very well might be a problem here, but I can't figure it out from just those AppVeyor logs.

**Comment by TrySound** [comment]
@jamestalmage  You mean the same with only pinkie?

**Comment by jamestalmage** [comment]
Can you make something simpler than cosmiconfig that causes a failed test?

Write it against AVA master and just submit a PR, or send me gist, whatever.

I just want something that helps me focus in on the problem, because right now I don't know where to start.

**Comment by TrySound** [comment]
@jamestalmage I'm doing this now

**Comment by jamestalmage** [comment]
Thanks

**Pull request merged**
