### PR TITLE
Add Promise.prototype.finally support

### PR DESCRIPTION
**Pull request by btd**

### CODE REVIEW

**Comment by btd** [comment]
Test failures related to `xo` and not code i added.

**Comment by floatdrop** [comment]
Thanks for the proposed functionality, but `finally` is not in the specification yet - therefore it could not be merged.

**Comment by btd** [comment]
@floatdrop it is stage 4 now (meaning it will be included in next es version). Or you are awaiting for official EcmaScript 20XX publishing?

**Comment by floatdrop** [comment]
@btd yep. Although I don’t think this project get full featured implementation of next EcmaScript specification (or I don’t see a reason, why it will be useful to anyone).

**Comment by btd** [comment]
@floatdrop this makes sense if you target node. But i personally use it in browser to ponyfill ie11 (it is still terribly 10% of our market share).
I am ok (feel free to close) if you do not want to change anything, i will just fork it to our company npm org. 
I am going to add support for browser events also.

**Comment by floatdrop** [comment]
@btd I would advise to use [es6-promise](https://github.com/stefanpenner/es6-promise) with `finally` support - seems like it has much more momentum.

**Comment by btd** [comment]
:+1: nah. It is 7kb vs 1kb. I will fork pinkie for my own needs.

**Pull request closed without merging**
